### ISSUE TITLE
H5端index.scss 文件的px单位不会转换为rem

### ISSUE THREAD

**Issue by fanerger** [lentoo/taro-skeleton#10]
如图：
![scss-px](https://user-images.githubusercontent.com/19178610/72319771-081bd180-36db-11ea-8587-6947cf9162a8.png)
***
当我把源码拷出来放到自己项目中引用就正常转换了
![scss-rem](https://user-images.githubusercontent.com/19178610/72319830-31d4f880-36db-11ea-86ff-6e511b31101c.jpg)

**Comment by lentoo** [comment]
我的能正常转换。可以提供一下demo吗？

**Comment by lentoo** [comment]
由于引用 `node_modules` 的模块，默认不会编译，所以需要额外给 H5 配置 `esnextModules`，在 taro 项目的 `config/index.js` 中新增如下配置项：
```
h5: {
  esnextModules: ['taro-skeleton']
}
```
