### ISSUE TITLE
编译会报错

### ISSUE THREAD

**Issue by candyAndBella** [lentoo/taro-skeleton#11]
![image](https://user-images.githubusercontent.com/34698384/77742647-c354d500-7051-11ea-886d-bf1f14463f23.png)
![image](https://user-images.githubusercontent.com/34698384/77742885-28102f80-7052-11ea-9615-7e8f5f2533ae.png)

啥都没干，页面上就加了两行
import Skeleton from 'taro-skeleton'
Skeleton title row={3} />

编译就报错，怀疑是不是需要安装一下
cnpm install -s taro-skeleton
然后又编译了一次
还是报错

**Comment by lentoo** [comment]
你的taro是什么版本？

**Comment by candyAndBella** [comment]
> 你的taro是什么版本？

1.2.26

**Comment by lentoo** [comment]
你用npm安装试试，晚点我看看是不是版本不兼容的问题

**Comment by candyAndBella** [comment]
> 你用npm安装试试，晚点我看看是不是版本不兼容的问题

嗯嗯，我刚才用npm安装成功了，但是编译还是报错

**Comment by lentoo** [comment]
> > 你用npm安装试试，晚点我看看是不是版本不兼容的问题
> 
> 嗯嗯，我刚才用npm安装成功了，但是编译还是报错

升级一下版本会报错吗

**Comment by candyAndBella** [comment]
升级2.0之后，微信开发者工具一直报错，现在进不去页面了

**Comment by lentoo** [comment]
升级一下taro版本可以解决
