### ISSUE TITLE
没有显示占位

### ISSUE THREAD

**Issue by lovesL** [lentoo/taro-skeleton#14]
<Skeleton  loading={loading} key={i} row={2} title  rowHeight={40} > 设置了这些属性 但是没有显示占位 loading 初始是true   版本是：taro-skeleton": "^1.1.4
![image](https://user-images.githubusercontent.com/27960630/79294177-1fe83900-7f08-11ea-9806-0bba34318ca4.png)
 请问是还需要设置什么属性吗

**Comment by lentoo** [comment]
不需要了，你可以先看看不设置loading，会不会显示

**Comment by lovesL** [comment]
> 不需要了，你可以先看看不设置loading，会不会显示

不加loading 会显示 但是这样不能控制占位了

**Comment by lentoo** [comment]
> > 不需要了，你可以先看看不设置loading，会不会显示
> 
> 不加loading 会显示 但是这样不能控制占位了

那可能的情况就是，页面加载完成后，loading已经被设置为false了。你可以调慢网速或者在真机上试试

**Comment by lovesL** [comment]
> > > 不需要了，你可以先看看不设置loading，会不会显示
> > 
> > 
> > 不加loading 会显示 但是这样不能控制占位了
> 
> 那可能的情况就是，页面加载完成后，loading已经被设置为false了。你可以调慢网速或者在真机上试试

我是在ajax请求code 是200我才会改变loading=false   我调试调试吧

**Comment by lentoo** [comment]
> > > > 不需要了，你可以先看看不设置loading，会不会显示
> > > 
> > > 
> > > 不加loading 会显示 但是这样不能控制占位了
> > 
> > 
> > 那可能的情况就是，页面加载完成后，loading已经被设置为false了。你可以调慢网速或者在真机上试试
> 
> 我是在ajax请求code 是200我才会改变loading=false 我调试调试吧

或者你设置一个按钮，进行loading的切换试试看有没有效果
