### ISSUE TITLE
可以自定义形状和颜色吗

### ISSUE THREAD

**Issue by txqcoder** [lentoo/taro-skeleton#15]
可以自定义形状和颜色吗

**Comment by lentoo** [comment]
自定义颜色的话之后可以加一个属性来控制，目前的话你可以使用全局样式覆盖一下。
自定义形状的话，没太明白这个使用的场景

**Comment by lentoo** [comment]
> 可以自定义形状和颜色吗
新增了自定义类名来控制内部样式
