### ISSUE TITLE
必须使用typescript吗，我的项目没有使用typescript,看来只能找找其他方案了

### ISSUE THREAD

**Issue by liuyanming9551** [lentoo/taro-skeleton#16]

**Comment by lentoo** [comment]
jsx 也是可以使用的

**Comment by liuyanming9551** [comment]
> jsx 也是可以使用的

有案例吗？我这边就是jsx，但是组件是不生效的

**Comment by lentoo** [comment]
> > jsx 也是可以使用的
> 
> 有案例吗？我这边就是jsx，但是组件是不生效的

自己公司的项目就是用的jsx，目前没发现有问题。你可以提供个案例我帮你看看

**Comment by liuyanming9551** [comment]
> > > jsx 也是可以使用的
> > 
> > 
> > 有案例吗？我这边就是jsx，但是组件是不生效的
> 
> 自己公司的项目就是用的jsx，目前没发现有问题。你可以提供个案例我帮你看看

原因找到了，昨天是我自己配置有问题，感谢
