### ISSUE TITLE
@taro3.0版本 准备适配吗？

### ISSUE THREAD

**Issue by wforguo** [lentoo/taro-skeleton#21]
@taro3.0版本 准备适配吗？

**Comment by lentoo** [comment]
> @taro3.0版本 准备适配吗？

在适配了，目前taro3.0版本还有一些问题。

**Comment by vivinbear** [comment]
请问一下作者 目前3.0版本的适配情况如何呢?

**Comment by lentoo** [comment]
**Taro3.0**已支持，下载最新版本即可
