### ISSUE TITLE
Skeleton导致taro swiper显示实销

### ISSUE THREAD

**Issue by namezpage18** [lentoo/taro-skeleton#28]
在Skeleton中写了swiper轮播，swiperItem标签上的position：absolute属性消失了导致后续图片都无法正常显示

**Comment by lentoo** [comment]
> 在Skeleton中写了swiper轮播，swiperItem标签上的position：absolute属性消失了导致后续图片都无法正常显示

能给个demo吗？我这边简单的试了下，没发现问题
