### ISSUE TITLE
关于图片骨架的疑惑

### ISSUE THREAD

**Issue by cmzz** [lentoo/taro-skeleton#30]
大家好。 有一个疑惑
```
<Skeleton title loading={true} row={1} />
    <Image onload={xxx}></Image>
</Skeleton>
```

这是一个图片骨架，当 loading = true的时候，图片不会加载。

期望的效果是，当loading= true 时，图片能够加载，在图片 onload时，更改 loading=false，显示图片。
请问这个能实现吗。

**Comment by lentoo** [comment]
目前是只有当loading为false时，才会渲染里面的东西。你想要的这种效果目前版本应该实现不了。需要改改代码

**Comment by cmzz** [comment]
嗯。 有 wxapp-img-loader-taro 处理类似的图片懒加载。 但是 wxapp-img-loader-taro 似乎许久没更新了。 在taro3中使用似乎有嵌套 setState 的问题。 希望能够支持一下呀

**Comment by lusongcai** [comment]
![image](https://user-images.githubusercontent.com/24311496/96847655-08c16f80-1486-11eb-9035-3043742bac6b.png)
![image](https://user-images.githubusercontent.com/24311496/96847714-18d94f00-1486-11eb-9f61-e2e08a95f186.png)
![image](https://user-images.githubusercontent.com/24311496/96848052-81283080-1486-11eb-917f-5426963a3f31.png)
你好，我使用TypeScript会报的警告，有什么办法解决吗

**Comment by lentoo** [comment]
> 嗯。 有 wxapp-img-loader-taro 处理类似的图片懒加载。 但是 wxapp-img-loader-taro 似乎许久没更新了。 在taro3中使用似乎有嵌套 setState 的问题。 希望能够支持一下呀

你这个效果推荐使用图片懒加载和占位图实现
