### ISSUE TITLE
关于使用className提示类型转换异常问题

### ISSUE THREAD

**Issue by lusongcai** [lentoo/taro-skeleton#31]
![image](https://user-images.githubusercontent.com/24311496/96848542-2511dc00-1487-11eb-8f4f-175659869ad4.png)
![image](https://user-images.githubusercontent.com/24311496/96848632-3b1f9c80-1487-11eb-8f2f-0364438920b4.png)
![image](https://user-images.githubusercontent.com/24311496/96848611-3529bb80-1487-11eb-8eef-b6400fd065a4.png)

你好，我使用TypeScript会报的警告，有什么办法解决吗

**Comment by lentoo** [comment]
更新下2.0.3版本
