### ISSUE TITLE
在taro最新稳定版3.0.14下，2.0.3运行出错 Super expression must either be null or a function

### ISSUE THREAD

**Issue by taniyi** [lentoo/taro-skeleton#32]
2.0.2 正常

**Comment by lentoo** [comment]
> 2.0.2 正常

我看看

**Comment by lentoo** [comment]
我在taro 3.0.14下正常、能给个demo吗？

**Comment by cocoyk** [comment]
遇到类似的问题 taro 3.1.0   taro-skeleton 2.0.3 小程序正常 h5报TypeError: Super expression must either be null or a function
