### ISSUE TITLE
no such file or directory, open 'E:\xxx\node_modules\_taro-skeleton@2.0.3@taro-skeleton\dist\react'   

### ISSUE THREAD

**Issue by lp13762436965** [lentoo/taro-skeleton#33]
正常使用, 报错,麻烦作者能看看, 
Taro版本 2.2.11
no such file or directory, open 'E:\xxx\node_modules\_taro-skeleton@2.0.3@taro-skeleton\dist\react'

**Comment by lentoo** [comment]
> 正常使用, 报错,麻烦作者能看看,
> Taro版本 2.2.11
> no such file or directory, open 'E:\xxx\node_modules_taro-skeleton@2.0.3@taro-skeleton\dist\react'

taro 2.x 版本用 taro-skeleton@1.2.2 试试

**Comment by lp13762436965** [comment]
> > 正常使用, 报错,麻烦作者能看看,
> > Taro版本 2.2.11
> > no such file or directory, open 'E:\xxx\node_modules_taro-skeleton@2.0.3@taro-skeleton\dist\react'
> 
> taro 2.x 版本用 taro-skeleton@1.2.2 试试

老哥,可以了, 但是不知道为啥有个ts报错, 说让我传个child
所需类型来自属性 "children"，在此处的 "IntrinsicAttributes & SkeletonProps & { children?: ReactNode; }" 类型上声明该属性

**Comment by lentoo** [comment]
应该是ts声明类型问题
