### ISSUE TITLE
taro 3 正常引入报错  引入版本为"taro-skeleton": "^2.0.3",

### ISSUE THREAD

**Issue by MrYeZiqing** [lentoo/taro-skeleton#34]
TypeError: Super expression must either be null or a function

**Comment by lentoo** [comment]
> TypeError: Super expression must either be null or a function

taro 版本是多少

**Comment by MrYeZiqing** [comment]
> > TypeError：超级表达式必须为null或函数
> 
> 芋头版本是多少

taro 的版本是3.0.18 ，我现在将taro-skeleton的版本将为 2.0.2 就可以使用了

**Comment by lentoo** [comment]
安装最新2.0.4的包
