### ISSUE TITLE
h5使用骨架屏报错

### ISSUE THREAD

**Issue by ponychoker** [lentoo/taro-skeleton#37]
`Uncaught (in promise) TypeError: Super expression must either be null or a function
    at _inherits (_index.mjs?7f0e:4)
    at eval (index.js?55c0:7)
    at eval (index.js?55c0:7)
    at Module../node_modules/taro-skeleton/dist/h5/components/Skeleton/index.js (0.js:148)`
已经在config文件中配置
`  h5: {
    esnextModules: ['taro-skeleton']
}`
小程序端使用正常, taro版本`3.2.0-canary.3`

**Comment by ponychoker** [comment]
> `Uncaught (in promise) TypeError: Super expression must either be null or a function at _inherits (_index.mjs?7f0e:4) at eval (index.js?55c0:7) at eval (index.js?55c0:7) at Module../node_modules/taro-skeleton/dist/h5/components/Skeleton/index.js (0.js:148)`
> 已经在config文件中配置
> ` h5: { esnextModules: ['taro-skeleton'] }`
> 小程序端使用正常, taro版本`3.2.0-canary.3`

已解决
taro@3.2.0-canary中
` function pxTransform(size: number, designWidth?: number): string`
需要第二个参数designWidth
你的`addUnit`方法中缺少此参数

**Comment by lentoo** [comment]
你用的是什么版本的`taro-skeleton`，我看新版的2.0.3的包 `addUnit` 方法 是有传默认的 `designWidth`的

**Comment by zq12580** [comment]
同样没有找到addUnit方法， 求解决办法

**Comment by lentoo** [comment]
安装最新 2.0.4 的包
