### ISSUE TITLE
className自定义类名加不上去，不生效

### ISSUE THREAD

**Issue by EricWong1994** [lentoo/taro-skeleton#39]
![image](https://user-images.githubusercontent.com/48429995/116062587-9e002380-a6b6-11eb-9336-4a680020ae53.png)

![image](https://user-images.githubusercontent.com/48429995/116062368-685b3a80-a6b6-11eb-87a4-1589cc8b374b.png)

**Comment by EricWong1994** [comment]
还有 1行写 4个 20%宽度的条咋写啊

**Comment by lentoo** [comment]
微信小程序端自定义类名有生效吗
