### ISSUE TITLE
npm i taro-skeleton 加载不了包，有遇到过吗 This is related to npm not being able to find a file.

### ISSUE THREAD

**Issue by Duanruilong** [lentoo/taro-skeleton#4]
npm  报错了

![image](https://user-images.githubusercontent.com/22052028/66993367-08b5c380-f0fe-11e9-9570-676710518fc9.png)

**Comment by lentoo** [comment]
> npm 报错了
> 
> ![image](https://user-images.githubusercontent.com/22052028/66993367-08b5c380-f0fe-11e9-9570-676710518fc9.png)

把 node_modules 删除重新安装试试

**Comment by Duanruilong** [comment]
删除了，Node版本也降低到稳定版本还是不行，yarn add taro-skeleton也是安装不上。。。。

**Comment by lentoo** [comment]
检查一下，应该是环境问题
