### ISSUE TITLE
Taro v3.2.10，npm run dev:h5后报错提示TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by G21iwenjun** [lentoo/taro-skeleton#46]
<img width="605" alt="Snipaste_2021-06-03_14-28-46" src="https://user-images.githubusercontent.com/25291272/120597841-22914f00-c478-11eb-80d1-8b4cd5edab83.png">

**Comment by zZfd** [comment]
+1

**Comment by lentoo** [comment]
我看看

**Comment by tingyuxuan2302** [comment]
> 我看看

解决了吗，兄台，我也遇到了

**Comment by lentoo** [comment]
已经修复了、安装最新包2.0.4
